name: prune repo

on:
  workflow_call:
  
jobs:
  clean-ghcr:
    name: Cleanup repo
    runs-on: ubuntu-latest    
    steps:
    
      - name: Delete old container
        uses: snok/container-retention-policy@v2.1.2
        with:
          image-names: buildah-*
          cut-off: 1 weeks ago UTC
          account-type: personal
          skip-tags: latest
          token: ${{ secrets.PAT }}
          
      - name: Delete pr containers
        uses: snok/container-retention-policy@v2.1.2
        with:
          image-names: buildah-*
          cut-off: 1 day ago UTC
          account-type: personal
          filter-tags: "pr-*"
          token: ${{ secrets.PAT }}
